SELECT * FROM ARTICLE
ORDER BY DESIGNATION ASC;

SELECT * FROM ARTICLE
ORDER BY PRIX DESC;

SELECT * FROM ARTICLE
WHERE DESIGNATION LIKE '%boulon%'
ORDER BY PRIX ASC;

SELECT * FROM ARTICLE
WHERE DESIGNATION LIKE '%sachet%';

SELECT * FROM ARTICLE 
WHERE DESIGNATION LIKE '%sachet%'
COLLATE utf8mb4_bin;


SELECT ARTICLE.*, FOURNISSEUR.NOM
FROM ARTICLE
JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
ORDER BY FOURNISSEUR.NOM ASC, ARTICLE.PRIX DESC;

SELECT ARTICLE.*
FROM ARTICLE
JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
WHERE FOURNISSEUR.NOM = 'Dubois & Fils';

SELECT AVG(ARTICLE.PRIX) AS MoyennePrix
FROM ARTICLE
JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
WHERE FOURNISSEUR.NOM = 'Dubois & Fils';

SELECT FOURNISSEUR.NOM, AVG(ARTICLE.PRIX) AS MoyennePrix
FROM ARTICLE
JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
GROUP BY FOURNISSEUR.NOM;

SELECT * FROM BON
WHERE DATE_CMDE BETWEEN '2019-03-01' AND '2019-04-05 12:00:00';

SELECT DISTINCT BON.ID, BON.NUMERO
FROM BON
JOIN COMPO ON BON.ID = COMPO.ID_BON
JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
WHERE ARTICLE.DESIGNATION LIKE '%boulon%';

SELECT DISTINCT BON.ID, BON.NUMERO, FOURNISSEUR.NOM
FROM BON
JOIN COMPO ON BON.ID = COMPO.ID_BON
JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
WHERE ARTICLE.DESIGNATION LIKE '%boulon%';

SELECT BON.ID, BON.NUMERO, SUM(ARTICLE.PRIX * COMPO.QTE) AS PrixTotal
FROM BON
JOIN COMPO ON BON.ID = COMPO.ID_BON
JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
GROUP BY BON.ID;

SELECT BON.ID, BON.NUMERO, COUNT(COMPO.ID_ART) AS NombreArticles
FROM BON
JOIN COMPO ON BON.ID = COMPO.ID_BON
GROUP BY BON.ID;

SELECT BON.NUMERO, COUNT(COMPO.ID_ART) AS NombreArticles
FROM BON
JOIN COMPO ON BON.ID = COMPO.ID_BON
GROUP BY BON.ID
HAVING SUM(COMPO.QTE) > 25;

SELECT SUM(ARTICLE.PRIX * COMPO.QTE) AS CoutTotalAvril
FROM BON
JOIN COMPO ON BON.ID = COMPO.ID_BON
JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
WHERE MONTH(BON.DATE_CMDE) = 4 AND YEAR(BON.DATE_CMDE) = YEAR(CURDATE());


SELECT SUM(ARTICLE.PRIX * COMPO.QTE) AS CoutAvril
FROM BON 
JOIN COMPO ON BON.ID = COMPO.ID_BON 
JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID 
WHERE MONTH(BON.DATE_CMDE) = 4 AND YEAR(BON.DATE_CMDE) = 2019;

